import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Profile() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         {/* Welcome to Next.js! */}
         {/* This is my new Next.js app! */}
        塚田大喜の自己紹介
        </h1>

        <p className={styles.description}>
          [経歴]　高専　→　SU
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="https://www.amazon.co.jp/Amazon-Video/b?ie=UTF8&node=2351649051" className={styles.card}>
            <h2>趣味 &rarr;</h2>
            <p>・映画鑑賞　・海外ドラマ</p>
          </a>

          <a href="https://pad.gungho.jp/member/index.html" className={styles.card}>
            <h2>好きなゲーム &rarr;</h2>
            <p>・パズドラ　・モンハン</p>
          </a>

          <a
            href="https://www.anaconda.com/products/distribution"
            className={styles.card}
          >
            <h2>使ったことがある言語 &rarr;</h2>
            <p>・C言語　・Python<br/>・Java</p>
          </a>

          <a
            href="https://one-piece.com/"
            className={styles.card}
          >
            <h2>好きな漫画 &rarr;</h2>
            <p>
              ・ONE PIECE　・呪術廻戦<br/>・ブルーロック<br/>　　　　
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
